from fastapi import FastAPI, HTTPException
from app.config.log_middleware import LoggingMiddleware

from app.api.requests.request_flow import router as request_flow_router
from app.config.mongodb import db_startup
from fastapi.middleware.cors import CORSMiddleware
import logging

logging.getLogger("pymongo").setLevel(logging.WARNING)

app = FastAPI(
    title="CyberGuard PTaaS",
    description="This Swagger documentation is generated by FastAPI",
    lifespan=db_startup,
)


app.include_router(request_flow_router, tags=["Request Flow"])
app.add_middleware(LoggingMiddleware)


origins = [
    "http://localhost:5173",   
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],       
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {"message": "Welcome to CyberGuard PTaaS"}


